### ISSUE TITLE
On/Off has weird behavior on MacOS (12.2.1)

### ISSUE THREAD

**Issue by mitchell486** [HiDeoo/toggler-vscode#17]
When I have the word `on`, and try to use toggler, it goes to `oy`. I have tried using the keyboard shortcut troubleshooter, but it appears to be something inside the extension. Also, if I have `off`, toggler toggles it to `on`, and then if I toggler it again, `on` still goes to `oy`. 

OS - macOS 12.2.1 (21D62) [MacBook Pro 15-inch, 2017]
VSCode Info:
```
Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:00:58.347Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.3.0
```

I originally had the key changed from `CTRL+R` to `CTRL+T`, and I tried reverting that setting, but the issue still persists.

Extension Information from VSCode:
```
Name: Toggler
Id: hideoo.toggler
Description: Toggle words and symbols
Version: 0.3.0
Publisher: HiDeoo
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=hideoo.toggler
```

If you need, I can try to get a .gif of this behavior. Thank HiDeoo for the wonderful tool! I use it daily! 🙏

**Comment by mitchell486** [comment]
I should have tested more, because I just found out what is happening. This is the same behavior described in Issue #1, however this is only happening when the cursor is at the end of the word.

If I select the entire word, it works as expected. I suspect this is a tough nut to crack, because if this were to behave how I originally expected, I assume you would have to:
1. Recognize and match until the beginning AND end of the current word, so if the cursor position were in the middle of a word, you'd have to go both directions. If it's in front of the word, go until you find a space behind, and vice versa for my case.
2. If there is no recognized word, try matching a subset of characters.
3. If there is no recognized subset of characters, match a single character.

I'm not sure you want to implement this feature. Sounds like a lot of work for minimal reward of babysitting silly end users like myself! 😂  So, if you would like to close this issue with expected behavior, I will completely understand! I will leave it open for now in case you want to do anything with it. Thank you again for the wonderful tool! 🙏  👍

**Comment by HiDeoo** [comment]
Thanks for your feedback, glad you like the extension :)

Did you add some custom toggles like one switching a `n` (`no` first letter maybe?) to a `y` (`yes` first letter maybe?)? I cannot manage to repro the issue on my end:

![demo](https://user-images.githubusercontent.com/494699/159129262-5cc1a0b7-7653-4858-bb42-1be5f53e44b6.gif)

Such a toggle could take precedence over [the default `on` -> `off` toggle](https://github.com/HiDeoo/toggler-vscode/blob/133afe0fc7d414851202b93bf37a5840531e35b1/src/defaults.json#L106). 

The order of the toggles is very important as more important ones should be defined before less important ones. This is visible in the default toggles for example where `["onFocus", "onBlur"]` is defined before `["on", "off"]`. If this was not the case, having the cursor before the word `onFocus` and triggering a toggle would bring to the world the beautiful `offFocus` when you obviously want `onBlur` ^^

This is also the reason why I added to the extension a setting to use or not the default toggles bundled with the extension, so that the rare users who would need a totally different configuration could still use the extension.

<img width="768" alt="Screenshot 2022-03-19 at 17 24 21" src="https://user-images.githubusercontent.com/494699/159129585-39e6e82f-aeeb-45a1-881c-06d7365fae52.png">

Regarding finding a way to fix this issue properly, for all cases, without breaking the current behavior, why still being able to customize all toggles, this is [a problem going back to 2017](https://github.com/HiDeoo/toggler/issues/1#issuecomment-309030115) with a similar Atom extension I developed at the time considering the APIs available in the editors without adding too much complexity to the code.

**Comment by mitchell486** [comment]
> Did you add some custom toggles like one switching a n (no first letter maybe?) to a y (yes first letter maybe?)?

Yup! I 100% did that And it makes perfect sense that this would take precedence and ruin the normal toggle. I'll likely remove that Y/N one that I have, since it causes this weird behavior. Thanks again for the great extension, I use it daily!
