### ISSUE TITLE
Inconsistent/confusing handling of cursor position

### ISSUE THREAD

**Issue by batanun** [HiDeoo/toggler-vscode#4]
It seems that it can toggle the word to the left or to the right of the cursor, which can be handy I guess, but can also be confusing and cause inconsistent behavior, especially combined with the fact that the cursor can end up in a different position after a toggle causing multiple toggles in a row to not always circle back to the original value.

For example:

Use case 1:
The text: "**getCustomInput**"
Cursor position: before the word "**get**"
Toggle-configuration for the word "custom": `<not set`>
Toggle result: "**getCustomInput**" -> "**setCustomInput**" -> "**getCustomInput**"
Cursor movement: before the word "**get**" -> after the word "**set**" -> after the word "**get**"
Expected: same toggle result, but with the cursor remaining before the word "**get**"/"**set**"

Use case 2:
The text: "**getFirstInput**"
Cursor position: before the word "**get**"
Toggle-configuration for the word "first": "**last**"
Toggle result: "**getFirstInput**" -> "**setFirstInput**" -> "**setLastInput**" -> "**setLastOutput**" -> "**setLastInput**" -> "**setLastOutput**" ...
Cursor movement: before the word "**get**" -> after the word "**set**" -> after the word "**Last**" -> after the word "**In**" -> after the word "**Out**" -> after the word "**In**" ...
Expected toggle result: "**getFirstInput**" -> "**setFirstInput**" -> "**getFirstInput**"
Expected cursor movement: staying before the word "**get**"/"**set**"

**Comment by HiDeoo** [comment]
Thanks for the feedback.

This is not something that has been bothering me as I guess it's the output I expect altho I can see how some people may expect the behavior you describe.

When I have the time to finish the next version, I'll add an option for this, or maybe a different shortcut or maybe even both, not sure yet.

**Comment by HiDeoo** [comment]
Finally got back to this issue, turns out implementing this is a bit annoying.

The cursor moving is actually the expected behavior for the code we're currently using. Instead of replacing a word when we don't have a selection, we're removing it and inserting the new word, which cause the cursor to move to the end of the word.

The reason behind this particular behavior is due to [this issue](https://github.com/Microsoft/vscode/issues/32058) in VS Code.

I just tried implementing a proof-of-concept where I manually move back the cursor to its initial position after an edit. Unfortunately, on top of being  a pain for multiple cursor as edits are asynchronous, it also adds a very annoying visual glitch where you see the cursor moving back and forth after an edit.

I think I'll just wait for the `forceMoveMarkers` flag described in the linked issue to become part of the public API before implementing this option.
